class Border(int): ...

BORDER_DEFAULT: Border
BORDER_NONE: Border
BORDER_STATIC: Border
BORDER_SIMPLE: Border
BORDER_RAISED: Border
BORDER_SUNKEN: Border
BORDER_DOUBLE: Border
BORDER_THEME: Border
BORDER_MASK: Border
