from typing import Optional

from .._core import PyApp, Point, Size

class App(PyApp):
    def  __init__(self, redirect: bool = False, filename: Optional[str] = None,
                        useBestVisual: bool = False, clearSigInt: bool = True) -> None: ...
    @staticmethod
    def  Get() -> App: ...
    def MainLoop(self) -> int: ...
    def OnPreInit(self) -> None: ...
    def RedirectStdio(self, filename: Optional[str] = None) -> None: ...
    def RestoreStdio(self) -> None: ...
    def SetOutputWindowAttributes(self, title: Optional[str] = None, pos: Optional[Point] = None,
                                        size: Optional[Size] = None) -> None: ...
    #def  SetTopWindow(self, frame: Frame) -> None: ... # another implementation in PyApp mypy complaining that they are incompatable
    def  __del__(self) -> None: ...
