from typing import Optional
from ._wx_PyApp import PyApp
from ._wx_Point import Point
from ._wx_Size import Size
from ._wx_Frame import Frame

class App(PyApp):
    def  __init__(self, redirect: bool = False, filename: Optional[str] = None,
                        useBestVisual: bool = False, clearSigInt: bool = True) -> None: ...
    @staticmethod
    def  Get() -> App: ...
    def MainLoop(self) -> None: ...
    def OnPreInit(self) -> None: ...
    def RedirectStdio(self, filename: Optional[str] = None) -> None: ...
    def RestoreStdio(self) -> None: ...
    def SetOutputWindowAttributes(self, title: Optional[str] = None, pos: Optional[Point] = None,
                                        size: Optional[Size] = None) -> None: ...
    def  SetTopWindow(self, frame: Frame) -> None: ...
    def  __del__(self) -> None: ...
