from typing import overload, Any
from ._wx_EvtHandler import EvtHandler
from ._core._wx_StandardID import ID_ANY
from ._wx_Point import Point, DefaultPosition
from ._wx_Size import Size, DefaultSize
from ._wx_WindowBase import WindowBase
from ._core._wx_Orientation import Orientation, BOTH

PanelNameStr: str
class Window(WindowBase):
    @overload
    def __init__ (self) -> None: ...
    @overload
    def __init__ (self, parent: Window, id: int = ID_ANY,
                        pos: Point = DefaultPosition, size: Size = DefaultSize,
                        style: int = 0, name: str = PanelNameStr) -> None : ...
    def  AcceptsFocus(self) -> bool: ...
    def AcceptsFocusFromKeyboard(self) -> bool: ...
    def AcceptsFocusRecursively(self) -> bool: ...
    def AddChild(self, child: WindowBase) -> None: ...
    def AdjustForLayoutDirection(self, x: int, width: int, widthTotal: int) -> int: ...# documentation says return type is wx.Coord. experimentation produces an int
    def AlwaysShowScrollbars(self, hflag: bool = True, vflag: bool = True) -> None: ...
    def AssociateHandle(self, handle: Any) -> None: ... #not sure yet what a "handle" is
    def BeginRepositioningChildren(self) -> bool: ...
    def CacheBestSize(self, size: Size) -> None: ...
    def CanAcceptFocus(self) -> bool: ...
    def CanAcceptFocusFromKeyboard(self) -> bool: ...
    def CanScroll(self, orient: Orientation) -> bool: ...
    def CanSetTransparent(self) -> bool: ...
    def CaptureMouse(self) -> None: ...
    def Center(self, dir: Orientation = BOTH) -> None: ...
