from typing import overload, Any, Optional
from . import siplib
class Object(siplib.wrapper):
    #ClassInfo: ? documentation says its here. experementatios don't see it.
    ClassName: str
    RefData: Optional[Any] # unknown type (App() has None)
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: Object): ...
    def Destroy(self) -> None: ...
    #def GetClassInfo(self) -> ClassInfo # in documentation but does not apear to be in emplemenation
    def GetClassName(self) -> str: ... # doc says return type is wx.Char but experiments say str
    def GetRefData(self) -> Optional[Any] : ... # return type in documentation wx.ObjectRefData but cant find through experimenation
    def IsSameAs(self, obj: Object) -> bool: ...
    def Ref(self, clone: Object) -> None: ...
    def SetRefData(self, data: Any) -> None: ... # Attribute type unsure
    def UnRef(self) -> None: ...
    def UnShare(self) -> None: ...
